### ISSUE TITLE
Código não tá legível

### ISSUE THREAD

**Issue by pedrolemoz** [flavisXavier/random-maze#1]
## Tome vergonha na cara e deixe de ser um programador alfabético!

Não dá pra ler um código que usa letras como variáveis. Usar nomes mais descritivos ajuda muito a entender o contexto. Isso não atrapalha na performance pois no final, o compilador **transforma as  variáveis em tokens**.

**Comment by jsericksk** [comment]
Ih, eu não deixava, hein. Chamou de corno
